/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.averi.patchowe;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Patrick
 */
public class MyMoney extends javax.swing.JFrame {
	private Double GB_Bar;
	private Double GB_Bankomat;
	private Double GB_Summe;
	private Double Schulden;
	private String TransArt;
	
	DecimalFormat f;

	/**
	 * Creates new form MyMoney
	 */
	public MyMoney() {
		this.f = new DecimalFormat("#,##0.00 €");
		this.GB_Summe = 0.0;
		this.GB_Bankomat = 0.0;
		this.GB_Bar = 0.0;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_transaktion = new javax.swing.JDialog();
        lbl_trans_betrag = new javax.swing.JLabel();
        sp_trans_betrag = new javax.swing.JSpinner();
        btn_trans_durchführen = new javax.swing.JButton();
        btn_trans_abbrechen = new javax.swing.JButton();
        cbox_trans_konto = new javax.swing.JComboBox();
        lbl_trans_konto = new javax.swing.JLabel();
        lbl_geldbestand_derzeitig = new javax.swing.JLabel();
        txt_geldbestand_derzeitig = new javax.swing.JTextField();
        lbl_geldbestand_schulden = new javax.swing.JLabel();
        txt_geldbestand_schulden = new javax.swing.JTextField();
        pnl_aufteilung = new javax.swing.JPanel();
        lbl_aufteilung_bar = new javax.swing.JLabel();
        txt_aufteilung_bar = new javax.swing.JTextField();
        txt_aufteilung_bankomat = new javax.swing.JTextField();
        lbl_aufteilung_bankomat = new javax.swing.JLabel();
        pnl_aktionen = new javax.swing.JPanel();
        btn_aktionen_transaktion = new javax.swing.JButton();
        btn_aktionen_schliessen = new javax.swing.JButton();
        btn_aktionen_changebalance = new javax.swing.JButton();
        txt_unterschied = new javax.swing.JTextField();
        lbl_unterschied = new javax.swing.JLabel();

        dlg_transaktion.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dlg_transaktion.setResizable(false);
        dlg_transaktion.setType(java.awt.Window.Type.UTILITY);
        dlg_transaktion.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlg_transaktionWindowOpened(evt);
            }
        });

        lbl_trans_betrag.setText("Betrag:");

        sp_trans_betrag.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.5d)));
        sp_trans_betrag.setEditor(new javax.swing.JSpinner.NumberEditor(sp_trans_betrag, "0.00"));

        btn_trans_durchführen.setText("jButton1");
        btn_trans_durchführen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trans_durchführenActionPerformed(evt);
            }
        });

        btn_trans_abbrechen.setText("Abbrechen");
        btn_trans_abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trans_abbrechenActionPerformed(evt);
            }
        });

        cbox_trans_konto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bar", "Bankomat" }));

        lbl_trans_konto.setText("Konto:");

        javax.swing.GroupLayout dlg_transaktionLayout = new javax.swing.GroupLayout(dlg_transaktion.getContentPane());
        dlg_transaktion.getContentPane().setLayout(dlg_transaktionLayout);
        dlg_transaktionLayout.setHorizontalGroup(
            dlg_transaktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_transaktionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_transaktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg_transaktionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_trans_abbrechen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_trans_durchführen))
                    .addGroup(dlg_transaktionLayout.createSequentialGroup()
                        .addComponent(lbl_trans_konto)
                        .addGap(8, 8, 8)
                        .addComponent(cbox_trans_konto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_transaktionLayout.createSequentialGroup()
                        .addComponent(lbl_trans_betrag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_trans_betrag)))
                .addContainerGap())
        );
        dlg_transaktionLayout.setVerticalGroup(
            dlg_transaktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_transaktionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_transaktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_trans_konto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_trans_konto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlg_transaktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_trans_betrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_trans_betrag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlg_transaktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_trans_durchführen)
                    .addComponent(btn_trans_abbrechen))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mein Geldbestand");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lbl_geldbestand_derzeitig.setText("Mein derzeitiger Geldbestand:");

        txt_geldbestand_derzeitig.setEditable(false);

        lbl_geldbestand_schulden.setText("Mein Geldbestand nach Begleichung aller Schulden:");

        txt_geldbestand_schulden.setEditable(false);

        pnl_aufteilung.setBorder(javax.swing.BorderFactory.createTitledBorder("Aufteilung"));

        lbl_aufteilung_bar.setText("Bar:");

        txt_aufteilung_bar.setEditable(false);

        txt_aufteilung_bankomat.setEditable(false);

        lbl_aufteilung_bankomat.setText("Bankomat:");

        javax.swing.GroupLayout pnl_aufteilungLayout = new javax.swing.GroupLayout(pnl_aufteilung);
        pnl_aufteilung.setLayout(pnl_aufteilungLayout);
        pnl_aufteilungLayout.setHorizontalGroup(
            pnl_aufteilungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_aufteilungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_aufteilungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_aufteilung_bankomat)
                    .addComponent(lbl_aufteilung_bar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_aufteilungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_aufteilung_bar)
                    .addComponent(txt_aufteilung_bankomat, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_aufteilungLayout.setVerticalGroup(
            pnl_aufteilungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aufteilungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_aufteilungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_aufteilung_bar)
                    .addComponent(txt_aufteilung_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_aufteilungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_aufteilung_bankomat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_aufteilung_bankomat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_aktionen.setBorder(javax.swing.BorderFactory.createTitledBorder("Aktionen"));

        btn_aktionen_transaktion.setText("Geld hinzufügen/abziehen");
        btn_aktionen_transaktion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aktionen_transaktionActionPerformed(evt);
            }
        });

        btn_aktionen_schliessen.setText("Schließen");
        btn_aktionen_schliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aktionen_schliessenActionPerformed(evt);
            }
        });

        btn_aktionen_changebalance.setText("Kontostand ändern");
        btn_aktionen_changebalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aktionen_changebalanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_aktionenLayout = new javax.swing.GroupLayout(pnl_aktionen);
        pnl_aktionen.setLayout(pnl_aktionenLayout);
        pnl_aktionenLayout.setHorizontalGroup(
            pnl_aktionenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aktionenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_aktionenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_aktionen_transaktion, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(btn_aktionen_schliessen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_aktionen_changebalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_aktionenLayout.setVerticalGroup(
            pnl_aktionenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aktionenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_aktionen_transaktion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_aktionen_changebalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_aktionen_schliessen)
                .addContainerGap())
        );

        txt_unterschied.setEditable(false);

        lbl_unterschied.setText("Unterschied:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_aufteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_aktionen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_geldbestand_schulden)
                            .addComponent(lbl_geldbestand_derzeitig)
                            .addComponent(lbl_unterschied))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_unterschied)
                            .addComponent(txt_geldbestand_schulden)
                            .addComponent(txt_geldbestand_derzeitig))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_geldbestand_derzeitig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_geldbestand_derzeitig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_geldbestand_schulden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_geldbestand_schulden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_unterschied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_unterschied))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_aktionen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_aufteilung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aktionen_schliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aktionen_schliessenActionPerformed
        dispose();
    }//GEN-LAST:event_btn_aktionen_schliessenActionPerformed

    private void btn_aktionen_transaktionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aktionen_transaktionActionPerformed
        Object[] options = {"Abbrechen", "Abziehen", "Hinzufügen",};
		int ergebnis = JOptionPane.showOptionDialog(this,"Willst du Geld hinzufügen oder abziehen??",
            "Hinzufügen/Abziehen?",JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,options,null);
		if (ergebnis == 2) {
			TransArt = "add";
			dlg_transaktion.setLocationRelativeTo(null);
			dlg_transaktion.setTitle("Geld hinzufügen");
			btn_trans_durchführen.setText("Hinzufügen");
			dlg_transaktion.pack();
			dlg_transaktion.setVisible(true);
			
			
			//
		}
		else if (ergebnis == 1) {
			TransArt = "subtract";
			dlg_transaktion.setLocationRelativeTo(null);
			dlg_transaktion.setTitle("Geld abziehen");
			btn_trans_durchführen.setText("Abziehen");
			dlg_transaktion.pack();
			dlg_transaktion.setVisible(true);
			
			
			//MainMenu.infoBox(this, "Geld wurde erfolgreich vom Konto " + " abgezogen!", "Geld abgezogen!");
		}
		else {

		}

    }//GEN-LAST:event_btn_aktionen_transaktionActionPerformed

    private void dlg_transaktionWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlg_transaktionWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_dlg_transaktionWindowOpened

    private void btn_trans_abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trans_abbrechenActionPerformed
        dlg_transaktion.dispose();
    }//GEN-LAST:event_btn_trans_abbrechenActionPerformed

    private void btn_trans_durchführenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trans_durchführenActionPerformed
		SpinnerNumberModel sp_trans_betrag_model = (SpinnerNumberModel)sp_trans_betrag.getModel();
		switch (TransArt) {
			case "add":
				if (cbox_trans_konto.getSelectedIndex()==0) {
					GB_Bar = GB_Bar + sp_trans_betrag_model.getNumber().doubleValue();
					MainMenu.savevariable("GB_Bar", GB_Bar.toString());
				}
				else {
					GB_Bankomat = GB_Bankomat + sp_trans_betrag_model.getNumber().doubleValue();
					MainMenu.savevariable("GB_Bankomat", GB_Bankomat.toString());
				}
				MainMenu.infoBox(this, sp_trans_betrag_model.getNumber().doubleValue() + "€ wurden erfolgreich zum Konto "
						+ f.format(cbox_trans_konto.getSelectedItem()) + " hinzugefügt!", "Geld hinzugefügt!");
				dlg_transaktion.dispose();
				break;
			case "subtract":
				if (cbox_trans_konto.getSelectedIndex()==0) {
					GB_Bar = GB_Bar - sp_trans_betrag_model.getNumber().doubleValue();
					MainMenu.savevariable("GB_Bar", GB_Bar.toString());
				}
				else {
					GB_Bankomat = GB_Bankomat - sp_trans_betrag_model.getNumber().doubleValue();
					MainMenu.savevariable("GB_Bankomat", GB_Bankomat.toString());
				}
				MainMenu.infoBox(this, sp_trans_betrag_model.getNumber().doubleValue() + "€ wurden erfolgreich vom Konto "
						+ f.format(cbox_trans_konto.getSelectedItem()) + " abgezogen!", "Geld abgezogen!");
				dlg_transaktion.dispose();
				break;
			case "change":
				if (cbox_trans_konto.getSelectedIndex()==0) {
					GB_Bar = sp_trans_betrag_model.getNumber().doubleValue();
					MainMenu.savevariable("GB_Bar", GB_Bar.toString());
				}
				else {
					GB_Bankomat = sp_trans_betrag_model.getNumber().doubleValue();
					MainMenu.savevariable("GB_Bankomat", GB_Bankomat.toString());
				}
				MainMenu.infoBox(this, "Das Konto " + cbox_trans_konto.getSelectedItem() + " wurde erfolgreich auf "
						+ f.format(sp_trans_betrag_model.getNumber().doubleValue()) + " geändert!", "Kontostand geändert!");
				dlg_transaktion.dispose();
				
				break;
		}
		InfoRefresh();
    }//GEN-LAST:event_btn_trans_durchführenActionPerformed

    private void btn_aktionen_changebalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aktionen_changebalanceActionPerformed
        TransArt = "change";
		dlg_transaktion.setLocationRelativeTo(null);
		dlg_transaktion.setTitle("Kontostand ändern");
		btn_trans_durchführen.setText("Ändern");
		dlg_transaktion.pack();
		dlg_transaktion.setVisible(true);
    }//GEN-LAST:event_btn_aktionen_changebalanceActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        InfoRefresh();
    }//GEN-LAST:event_formWindowActivated

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MyMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MyMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MyMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MyMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MyMoney().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aktionen_changebalance;
    private javax.swing.JButton btn_aktionen_schliessen;
    private javax.swing.JButton btn_aktionen_transaktion;
    private javax.swing.JButton btn_trans_abbrechen;
    private javax.swing.JButton btn_trans_durchführen;
    private javax.swing.JComboBox cbox_trans_konto;
    private javax.swing.JDialog dlg_transaktion;
    private javax.swing.JLabel lbl_aufteilung_bankomat;
    private javax.swing.JLabel lbl_aufteilung_bar;
    private javax.swing.JLabel lbl_geldbestand_derzeitig;
    private javax.swing.JLabel lbl_geldbestand_schulden;
    private javax.swing.JLabel lbl_trans_betrag;
    private javax.swing.JLabel lbl_trans_konto;
    private javax.swing.JLabel lbl_unterschied;
    private javax.swing.JPanel pnl_aktionen;
    private javax.swing.JPanel pnl_aufteilung;
    private javax.swing.JSpinner sp_trans_betrag;
    private javax.swing.JTextField txt_aufteilung_bankomat;
    private javax.swing.JTextField txt_aufteilung_bar;
    private javax.swing.JTextField txt_geldbestand_derzeitig;
    private javax.swing.JTextField txt_geldbestand_schulden;
    private javax.swing.JTextField txt_unterschied;
    // End of variables declaration//GEN-END:variables

	private void InfoRefresh() {
		if (MainMenu.getvariable("GB_Bar") != null) {
			GB_Bar = Double.parseDouble(MainMenu.p.getProperty("GB_Bar"));
		}
		if (MainMenu.getvariable("GB_Bankomat") != null) {
			GB_Bankomat = Double.parseDouble(MainMenu.p.getProperty("GB_Bankomat"));
		}
		GB_Summe = GB_Bar + GB_Bankomat;
		Schulden = GB_Summe + MainMenu.summegesamt;
		double Unterschied = MainMenu.summegesamt;
		txt_aufteilung_bar.setText(f.format(GB_Bar));
		txt_aufteilung_bankomat.setText(f.format(GB_Bankomat));
		txt_geldbestand_derzeitig.setText(f.format(GB_Summe));
		txt_geldbestand_schulden.setText(f.format(Schulden));
		if (Unterschied >= 0) {
			txt_unterschied.setForeground(new Color(51,153,0));
		}
		else {
			txt_unterschied.setForeground(new Color(255,0,0));
		}
		txt_unterschied.setText(f.format(Unterschied));
	}
}
