/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.averi.patchowe;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick
 */
public class NewEntry extends javax.swing.JFrame {

    ArrayList al;
	int si_friends;
	
    
    double Betrag = 0;
    
    /**
     * Creates new form NeueTransaktion
     */
    public NewEntry() {
	//start = new Home();
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdiogrp_art = new javax.swing.ButtonGroup();
        lbl_freund = new javax.swing.JLabel();
        cbox_friends = new javax.swing.JComboBox<String>();
        btn_addfriend = new javax.swing.JButton();
        lbl_art = new javax.swing.JLabel();
        rdio_schuldet = new javax.swing.JRadioButton();
        rdio_ichschulde = new javax.swing.JRadioButton();
        lbl_betrag = new javax.swing.JLabel();
        sp_betrag = new javax.swing.JSpinner();
        btn_hinzufügen = new javax.swing.JButton();
        btn_Abbrechen = new javax.swing.JButton();
        lbl_beschreibung = new javax.swing.JLabel();
        txt_beschreibung = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Neuer Schuldeneintrag");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                refreshcombo(evt);
            }
        });

        lbl_freund.setText("Name auswählen:");

        btn_addfriend.setText("Neu..");
        btn_addfriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addfriendActionPerformed(evt);
            }
        });

        lbl_art.setText("Art:");

        rdiogrp_art.add(rdio_schuldet);
        rdio_schuldet.setSelected(true);
        rdio_schuldet.setText("Er/Sie schuldet");

        rdiogrp_art.add(rdio_ichschulde);
        rdio_ichschulde.setText("Ich schulde");

        lbl_betrag.setText("Betrag:");

        sp_betrag.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.5d)));
        sp_betrag.setEditor(new javax.swing.JSpinner.NumberEditor(sp_betrag, "0.00"));

        btn_hinzufügen.setText("Hinzufügen");
        btn_hinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hinzufügenActionPerformed(evt);
            }
        });

        btn_Abbrechen.setText("Abbrechen");
        btn_Abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AbbrechenActionPerformed(evt);
            }
        });

        lbl_beschreibung.setText("Beschreibung:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_freund)
                            .addComponent(lbl_art)
                            .addComponent(lbl_beschreibung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbox_friends, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdio_schuldet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdio_ichschulde)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_addfriend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txt_beschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_betrag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_betrag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Abbrechen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hinzufügen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_freund)
                    .addComponent(cbox_friends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addfriend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_art)
                    .addComponent(rdio_schuldet)
                    .addComponent(rdio_ichschulde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_beschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_beschreibung)
                    .addComponent(lbl_betrag)
                    .addComponent(sp_betrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Abbrechen)
                    .addComponent(btn_hinzufügen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param message
     * @param title
     */
    public void infoBox (String message, String title) {
	JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     *
     * @param message
     * @param title
     */
    public void errorBox (String message, String title) {
	JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
    }
    
    protected void createcon() {
	
    }
    
    
    
    protected void cboxrefresh() {
		try {
			MainMenu.SQL = "SELECT vorname, nachname FROM patchowe_personen";
			MainMenu.prepareStatement();
			MainMenu.rs = MainMenu.stmt.executeQuery();
			cbox_friends.removeAllItems();
			while (MainMenu.rs.next()) {
				cbox_friends.addItem(MainMenu.rs.getString("vorname") + " " + MainMenu.rs.getString("nachname"));
			}
			if (si_friends >= 0) {
				cbox_friends.setSelectedIndex(si_friends);
			}
		} catch (SQLException ex) {
			this.errorBox("Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
		}
    }
    
    private void btn_addfriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addfriendActionPerformed
        NewFriend newfriend = new NewFriend();
        newfriend.setVisible(true);
        //dlg_addfriend.setVisible(true);
    }//GEN-LAST:event_btn_addfriendActionPerformed

    private void btn_AbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AbbrechenActionPerformed
        dispose();  
    }//GEN-LAST:event_btn_AbbrechenActionPerformed

    @SuppressWarnings("empty-statement")
    private void btn_hinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hinzufügenActionPerformed
	try {
	    String gew;
	    String idString = null;
	    
	    gew = cbox_friends.getSelectedItem().toString();
	    String[] splitResult = gew.split(" ");
	    Calendar calendar = Calendar.getInstance();
	    java.util.Date utilDate = calendar.getTime();
	    java.sql.Date currentDate = new java.sql.Date(utilDate.getTime());
		Betrag = (double) sp_betrag.getValue();
	    
	    
	    MainMenu.SQL = "SELECT id FROM patchowe_personen WHERE vorname = ? AND nachname = ?";
	    MainMenu.prepareStatement();
	    MainMenu.stmt.setString(1, splitResult[0]);
	    MainMenu.stmt.setString(2, splitResult[1]);
	    MainMenu.rs = MainMenu.stmt.executeQuery();
	    
	    if (MainMenu.rs.next()) {
		idString=MainMenu.rs.getString(1);
	    }
	    
	    MainMenu.SQL = "INSERT INTO patchowe_transaktionen (pid, datum, betrag, beschreibung) VALUES ( ?, ?, ?, ?)";
        MainMenu.prepareStatement();
        MainMenu.stmt.setInt(1, Integer.parseInt(idString));
        MainMenu.stmt.setDate(2, currentDate);
        if (rdio_schuldet.isSelected()) {MainMenu.stmt.setDouble(3, (double) sp_betrag.getValue());} else {MainMenu.stmt.setDouble(3, -Betrag);}
		MainMenu.stmt.setString(4, txt_beschreibung.getText());
        MainMenu.stmt.execute();
		MainMenu.stmt.closeOnCompletion();
		txt_beschreibung.setText("");
		sp_betrag.setValue(0);
	    
	    this.infoBox("Der Schuldeneintrag für " + cbox_friends.getSelectedItem().toString() + " wurde erfolgreich erstellt!",
		    "Eintragung erfolgreich");
	    
	} catch (SQLException ex) {
	    this.errorBox("Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
	}
    }//GEN-LAST:event_btn_hinzufügenActionPerformed

    private void refreshcombo(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_refreshcombo
        cboxrefresh();
    }//GEN-LAST:event_refreshcombo

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        
		si_friends = cbox_friends.getSelectedIndex();
    }//GEN-LAST:event_formWindowLostFocus

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(NewEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
		@Override
	    public void run() {
		new NewEntry().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Abbrechen;
    private javax.swing.JButton btn_addfriend;
    private javax.swing.JButton btn_hinzufügen;
    protected javax.swing.JComboBox<String> cbox_friends;
    private javax.swing.JLabel lbl_art;
    private javax.swing.JLabel lbl_beschreibung;
    private javax.swing.JLabel lbl_betrag;
    private javax.swing.JLabel lbl_freund;
    private javax.swing.JRadioButton rdio_ichschulde;
    private javax.swing.JRadioButton rdio_schuldet;
    private javax.swing.ButtonGroup rdiogrp_art;
    private javax.swing.JSpinner sp_betrag;
    private javax.swing.JTextField txt_beschreibung;
    // End of variables declaration//GEN-END:variables

}