/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.averi.patchowe;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick
 */
public class NewFriend extends javax.swing.JFrame {

    ResultSet rs;
    NewEntry newtrans;
    String SQL;
    
    
    
    /**
     * Creates new form dlg_addfriend
     */
    public NewFriend() {
	newtrans = new NewEntry();
	SQL = MainMenu.SQL;
	newtrans.createcon();
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_zusatzinfo = new javax.swing.JTextField();
        txt_nachname = new javax.swing.JTextField();
        btn_hinzufügen = new javax.swing.JButton();
        lbl_nachname = new javax.swing.JLabel();
        lbl_vorname = new javax.swing.JLabel();
        txt_vorname = new javax.swing.JTextField();
        lbl_zusatzinformation = new javax.swing.JLabel();
        btn_schliessen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Neuer Freund");
        setResizable(false);

        btn_hinzufügen.setText("Hinzufügen");
        btn_hinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hinzufügenActionPerformed(evt);
            }
        });

        lbl_nachname.setText("Nachname:");

        lbl_vorname.setText("Vorname:");

        lbl_zusatzinformation.setText("Zusatzinformation:");

        btn_schliessen.setText("Schließen");
        btn_schliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_schliessenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_schliessen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hinzufügen))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_zusatzinformation)
                            .addComponent(lbl_nachname)
                            .addComponent(lbl_vorname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_vorname, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txt_nachname)
                            .addComponent(txt_zusatzinfo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_vorname)
                    .addComponent(txt_vorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nachname)
                    .addComponent(txt_nachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_zusatzinformation)
                    .addComponent(txt_zusatzinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hinzufügen)
                    .addComponent(btn_schliessen))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     *
     * @param message
     * @param title
     */
    public void infoBox (String message, String title) {
	JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     *
     * @param message
     * @param title
     */
    public void errorBox (String message, String title) {
	JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
    }
    
    private void prepareStatement() {
	try {
	    
	    MainMenu.stmt = MainMenu.con.prepareStatement(SQL);
	} catch (Exception ex) {
	    this.errorBox("Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
	}
    }
    
    
    private void btn_hinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hinzufügenActionPerformed
        try {

            if (txt_vorname.getText().length() == 0 && txt_nachname.getText().length() == 0) {
                this.errorBox("Sie haben nicht alle nötigen Felder ausgefüllt!", "Füllen Sie alle Felder aus!");
            } else {
                SQL = "INSERT INTO patchowe_personen (vorname, nachname, kommentar) VALUES ( ?, ?, ?)";
                this.prepareStatement();
                MainMenu.stmt.setString(1, txt_vorname.getText());
                MainMenu.stmt.setString(2, txt_nachname.getText());
                MainMenu.stmt.setString(3, txt_zusatzinfo.getText());
                MainMenu.stmt.execute();
                this.infoBox("Die Daten wurden erfolgreich hinzugefügt!", "Daten hinzugefügt!");
				MainMenu.stmt.closeOnCompletion();
				txt_vorname.setText("");
				txt_nachname.setText("");
				txt_zusatzinfo.setText("");
            }

        }
        catch (SQLException ex) {
            this.errorBox("Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");

        }
    }//GEN-LAST:event_btn_hinzufügenActionPerformed

    private void btn_schliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_schliessenActionPerformed
        dispose();
    }//GEN-LAST:event_btn_schliessenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(NewFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(NewFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(NewFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(NewFriend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new NewFriend().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hinzufügen;
    private javax.swing.JButton btn_schliessen;
    private javax.swing.JLabel lbl_nachname;
    private javax.swing.JLabel lbl_vorname;
    private javax.swing.JLabel lbl_zusatzinformation;
    private javax.swing.JTextField txt_nachname;
    private javax.swing.JTextField txt_vorname;
    private javax.swing.JTextField txt_zusatzinfo;
    // End of variables declaration//GEN-END:variables
}
