/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.averi.patchowe;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Patrick
 */
public class NewRepayment extends javax.swing.JFrame {
	private NewEntry newentry;
	private int si_friends;
	private ResultSet rstrans;
	private ResultSet rsinfo;
	private int SelectedID;
	private DecimalFormat f = new DecimalFormat("#0.00 €");
	private SimpleDateFormat d = new SimpleDateFormat("dd.MMMM.yyyy");

	/**
	 * Creates new form NewRepayment
	 */
	public NewRepayment() {
		initComponents();
		
		//Frames
		newentry = new NewEntry();
		
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdiogrp_sv = new javax.swing.ButtonGroup();
        lbl_freund = new javax.swing.JLabel();
        cbox_freund = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        cbox_transaktion = new javax.swing.JComboBox<String>();
        chk_teilrückzahlung = new javax.swing.JCheckBox();
        sp_betrag = new javax.swing.JSpinner();
        btn_begleichen = new javax.swing.JButton();
        btn_abbrechen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_betrag = new javax.swing.JLabel();
        lbl_beschreibung = new javax.swing.JLabel();
        lbl_datum = new javax.swing.JLabel();
        txt_betrag = new javax.swing.JTextField();
        txt_beschreibung = new javax.swing.JTextField();
        txt_datum = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        rdio_schuld = new javax.swing.JRadioButton();
        rdio_verliehen = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Neue Rückzahlung");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lbl_freund.setText("Name auswählen:");

        cbox_freund.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_freund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_freundActionPerformed(evt);
            }
        });

        jLabel1.setText("Transaktion auswählen:");

        cbox_transaktion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_transaktion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_transaktionActionPerformed(evt);
            }
        });

        chk_teilrückzahlung.setText("Teilrückzahlung");
        chk_teilrückzahlung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_teilrückzahlungActionPerformed(evt);
            }
        });

        sp_betrag.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.5d)));
        sp_betrag.setEditor(new javax.swing.JSpinner.NumberEditor(sp_betrag, "0.00"));
        sp_betrag.setEnabled(false);

        btn_begleichen.setText("Begleichen");
        btn_begleichen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_begleichenActionPerformed(evt);
            }
        });

        btn_abbrechen.setText("Abbrechen");
        btn_abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abbrechenActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        lbl_betrag.setText("Betrag:");

        lbl_beschreibung.setText("Beschreibung:");

        lbl_datum.setText("Datum:");

        txt_betrag.setEditable(false);
        txt_betrag.setText("betrag");

        txt_beschreibung.setEditable(false);
        txt_beschreibung.setText("beschreibung");

        txt_datum.setEditable(false);
        txt_datum.setText("datum");

        lbl_name.setText("Name:");

        txt_name.setEditable(false);
        txt_name.setText("name");

        rdiogrp_sv.add(rdio_schuld);
        rdio_schuld.setText("Schuld");
        rdio_schuld.setFocusable(false);

        rdiogrp_sv.add(rdio_verliehen);
        rdio_verliehen.setText("Verliehen");
        rdio_verliehen.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_name)
                    .addComponent(lbl_datum)
                    .addComponent(lbl_beschreibung)
                    .addComponent(lbl_betrag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdio_schuld)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdio_verliehen)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(txt_betrag, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_beschreibung, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_datum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdio_verliehen)
                    .addComponent(rdio_schuld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_betrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_betrag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_beschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_beschreibung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_datum))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_freund))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox_freund, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbox_transaktion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(chk_teilrückzahlung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_betrag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_abbrechen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_begleichen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_freund)
                    .addComponent(cbox_freund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbox_transaktion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_betrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_teilrückzahlung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_begleichen)
                    .addComponent(btn_abbrechen))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chk_teilrückzahlungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_teilrückzahlungActionPerformed
        sp_betrag.setEnabled(chk_teilrückzahlung.isSelected());
		if (chk_teilrückzahlung.isSelected()) {
			btn_begleichen.setText("Durchführen");
		}
		else {
			btn_begleichen.setText("Begleichen");
		}
    }//GEN-LAST:event_chk_teilrückzahlungActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        namesrefresh();
    }//GEN-LAST:event_formWindowActivated

    private void cbox_freundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_freundActionPerformed
        if (cbox_freund.getSelectedItem() != null) {
			transrefresh();
			txt_name.setText(cbox_freund.getSelectedItem().toString());
		}
		
    }//GEN-LAST:event_cbox_freundActionPerformed

    private void btn_begleichenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_begleichenActionPerformed
        if (chk_teilrückzahlung.isSelected() == false) {
			try {
				MainMenu.SQL = "DELETE FROM patchowe_transaktionen WHERE id = ?";
				MainMenu.prepareStatement();
				MainMenu.stmt.setInt(1, SelectedID);
				MainMenu.stmt.execute();
				
				MainMenu.infoBox(this, "Der Schuldeneintrag für " + txt_name.getText() + " in der Höhe von " + txt_betrag.getText()
						+ " wurde erfolgreich beglichen!", "Erfolgreich beglichen");
				
			} catch (SQLException ex) {
				MainMenu.errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
			}
		}
		else {
			try {
				MainMenu.SQL = "UPDATE patchowe_transaktionen SET betrag = betrag - ? WHERE id = ?";
				MainMenu.prepareStatement();
				MainMenu.stmt.setDouble(1, (double) sp_betrag.getValue());
				MainMenu.stmt.setInt(2, SelectedID);
				MainMenu.stmt.execute();
				MainMenu.infoBox(this, "Die Teilrückzahlung für " + txt_name.getText() + " in der Höhe von " + f.format(sp_betrag.getValue())
						+ " wurde erfolgreich durchgeführt!", "Erfolgreich durchgeführt!");
			} catch (SQLException ex) {
				Logger.getLogger(NewRepayment.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_btn_begleichenActionPerformed

    private void cbox_transaktionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_transaktionActionPerformed
        if (cbox_transaktion.getSelectedItem() != null) {
			inforefresh();
		}
    }//GEN-LAST:event_cbox_transaktionActionPerformed

    private void btn_abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abbrechenActionPerformed
        dispose();
    }//GEN-LAST:event_btn_abbrechenActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewRepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewRepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewRepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewRepayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new NewRepayment().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abbrechen;
    private javax.swing.JButton btn_begleichen;
    private javax.swing.JComboBox<String> cbox_freund;
    private javax.swing.JComboBox<String> cbox_transaktion;
    private javax.swing.JCheckBox chk_teilrückzahlung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_beschreibung;
    private javax.swing.JLabel lbl_betrag;
    private javax.swing.JLabel lbl_datum;
    private javax.swing.JLabel lbl_freund;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JRadioButton rdio_schuld;
    private javax.swing.JRadioButton rdio_verliehen;
    private javax.swing.ButtonGroup rdiogrp_sv;
    private javax.swing.JSpinner sp_betrag;
    private javax.swing.JTextField txt_beschreibung;
    private javax.swing.JTextField txt_betrag;
    private javax.swing.JTextField txt_datum;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

	private void namesrefresh() {
		try {
			MainMenu.SQL = "SELECT vorname, nachname FROM patchowe_personen";
			MainMenu.prepareStatement();
			MainMenu.rs = MainMenu.stmt.executeQuery();
			cbox_freund.removeAllItems();
			while (MainMenu.rs.next()) {
				cbox_freund.addItem(MainMenu.rs.getString("vorname") + " " + MainMenu.rs.getString("nachname"));
			}
			//if (si_friends >= 0) {
				//cbox_freund.setSelectedIndex(si_friends);
			//}
		} catch (SQLException ex) {
			MainMenu.errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
		}
	}
	
	private void transrefresh() {
		try {
			String sel;
			
			sel = cbox_freund.getSelectedItem().toString();
			
			String[] splitResult = sel.split(" ");
			
			String idString = null;
			
			MainMenu.SQL = "SELECT id FROM patchowe_personen WHERE vorname = ? AND nachname = ?";
			MainMenu.prepareStatement();
			MainMenu.stmt.setString(1, splitResult[0]);
			MainMenu.stmt.setString(2, splitResult[1]);
			rstrans = MainMenu.stmt.executeQuery();
			
			if (rstrans.next()) {
				idString=rstrans.getString(1);
			}
			
			
			MainMenu.SQL = "SELECT id, beschreibung, betrag "
					+ "FROM patchowe_transaktionen WHERE pid = ?";
			MainMenu.prepareStatement();
			MainMenu.stmt.setInt(1, Integer.parseInt(idString));
			rstrans = MainMenu.stmt.executeQuery();
			cbox_transaktion.removeAllItems();
			while (rstrans.next()) {
				cbox_transaktion.addItem(rstrans.getInt("id") + " - " + rstrans.getString("beschreibung")
						+ " - " + f.format(rstrans.getDouble("betrag")));
			}
			//if (si_friends >= 0) {
				//cbox_freund.setSelectedIndex(si_friends);
			//}
		} catch (SQLException ex) {
			MainMenu.errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
		}
	}
	
	private void inforefresh() {
		try {
			String sel;
			sel = cbox_transaktion.getSelectedItem().toString();
			String[] splitResult = sel.split(" - ");
			double Betrag;
			SelectedID = Integer.parseInt(splitResult[0]);
			
			MainMenu.SQL = "SELECT betrag, beschreibung, datum FROM patchowe_transaktionen WHERE id = ?";
			MainMenu.prepareStatement();
			MainMenu.stmt.setInt(1, SelectedID);
			rsinfo = MainMenu.stmt.executeQuery();
			if (rsinfo.next()) {
				Betrag = rsinfo.getDouble("betrag");
				
				if (Betrag >= 0) {
					rdio_verliehen.setSelected(true);
				}
				else {
					rdio_schuld.setSelected(true);
				}
				txt_betrag.setText(f.format(Math.abs(Betrag)));
				txt_beschreibung.setText(rsinfo.getString("beschreibung"));
				txt_datum.setText(d.format(rsinfo.getDate("datum")));
			}
			
		} catch (SQLException ex) {
			Logger.getLogger(NewRepayment.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
}
