/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.averi.patchowe;

import static at.averi.patchowe.MainMenu.errorBox;
import static at.averi.patchowe.MainMenu.infoBox;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Patrick
 */
public class VirtualPay extends javax.swing.JFrame {
	private double Produktwert;
	private double Maximalstück;
	private ResultSet rs_delete;
	private ResultSet rs_products;
	private ResultSet rs_info;
	private double Kapital;
	private final DecimalFormat euro;
	private double Gesamtpreis;
	private final DecimalFormat n;
	private int SelectedID;

	/**
	 * Creates new form VirtualPay
	 */
	public VirtualPay() {
		this.euro = new DecimalFormat("#,##0.00 €");
		this.n = new DecimalFormat("0");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_newproduct = new javax.swing.JDialog();
        btn_schliessen1 = new javax.swing.JButton();
        txt_np_name = new javax.swing.JTextField();
        lbl_np_kommentar = new javax.swing.JLabel();
        btn_hinzufügen = new javax.swing.JButton();
        lbl_np_wert = new javax.swing.JLabel();
        lbl_np_name = new javax.swing.JLabel();
        txt_np_kommentar = new javax.swing.JTextField();
        sp_np_wert = new javax.swing.JSpinner();
        dlg_deleteproduct = new javax.swing.JDialog();
        cbox_deleteproduct_products = new javax.swing.JComboBox<String>();
        btn_deleteproduct_löschen = new javax.swing.JButton();
        btn_deleteproduct_abbrechen = new javax.swing.JButton();
        dlg_changeproduct = new javax.swing.JDialog();
        btn_changeproduct_abbrechen = new javax.swing.JButton();
        cbox_changeproduct_products = new javax.swing.JComboBox<String>();
        btn_changeproduct_ändern = new javax.swing.JButton();
        pnl_trans = new javax.swing.JPanel();
        lbl_cp_info_wert = new javax.swing.JLabel();
        lbl_cp_info_kommentar = new javax.swing.JLabel();
        txt_cp_info_kommentar = new javax.swing.JTextField();
        lbl_cp_info_name = new javax.swing.JLabel();
        sp_cp_info_wert = new javax.swing.JSpinner();
        txt_cp_info_name = new javax.swing.JTextField();
        cbox_products = new javax.swing.JComboBox<String>();
        lbl_produkt = new javax.swing.JLabel();
        pnl_berechnungen = new javax.swing.JPanel();
        lbl_stück = new javax.swing.JLabel();
        sp_stück = new javax.swing.JSpinner();
        btn_max = new javax.swing.JButton();
        lbl_preis = new javax.swing.JLabel();
        txt_preis = new javax.swing.JTextField();
        lbl_restgeld = new javax.swing.JLabel();
        txt_restgeld = new javax.swing.JTextField();
        btn_newproduct = new javax.swing.JButton();
        btn_schliessen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        m_produkte = new javax.swing.JMenu();
        mitem_produkt_löschen = new javax.swing.JMenuItem();
        mitem_produkt_ändern = new javax.swing.JMenuItem();
        m_einkauf = new javax.swing.JMenu();
        mitem_einkauferstellen = new javax.swing.JMenuItem();
        m_lookeinkauf = new javax.swing.JMenu();

        dlg_newproduct.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlg_newproduct.setTitle("Neues Produkt");

        btn_schliessen1.setText("Schließen");
        btn_schliessen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_schliessen1ActionPerformed(evt);
            }
        });

        lbl_np_kommentar.setText("Kommentar:");

        btn_hinzufügen.setText("Hinzufügen");
        btn_hinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hinzufügenActionPerformed(evt);
            }
        });

        lbl_np_wert.setText("Wert:");

        lbl_np_name.setText("Name:");

        sp_np_wert.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.5d)));
        sp_np_wert.setEditor(new javax.swing.JSpinner.NumberEditor(sp_np_wert, "0.00"));

        javax.swing.GroupLayout dlg_newproductLayout = new javax.swing.GroupLayout(dlg_newproduct.getContentPane());
        dlg_newproduct.getContentPane().setLayout(dlg_newproductLayout);
        dlg_newproductLayout.setHorizontalGroup(
            dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_newproductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_newproductLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_schliessen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hinzufügen))
                    .addGroup(dlg_newproductLayout.createSequentialGroup()
                        .addGroup(dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_np_kommentar)
                            .addComponent(lbl_np_wert)
                            .addComponent(lbl_np_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_np_name, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txt_np_kommentar)
                            .addComponent(sp_np_wert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap())
        );
        dlg_newproductLayout.setVerticalGroup(
            dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_newproductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_np_name)
                    .addComponent(txt_np_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_np_wert)
                    .addComponent(sp_np_wert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_np_kommentar)
                    .addComponent(txt_np_kommentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlg_newproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hinzufügen)
                    .addComponent(btn_schliessen1))
                .addContainerGap())
        );

        dlg_deleteproduct.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlg_deleteproduct.setTitle("Produkt löschen");
        dlg_deleteproduct.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlg_deleteproductWindowActivated(evt);
            }
        });

        cbox_deleteproduct_products.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_deleteproduct_löschen.setText("Löschen");
        btn_deleteproduct_löschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteproduct_löschenActionPerformed(evt);
            }
        });

        btn_deleteproduct_abbrechen.setText("Abbrechen");
        btn_deleteproduct_abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteproduct_abbrechenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg_deleteproductLayout = new javax.swing.GroupLayout(dlg_deleteproduct.getContentPane());
        dlg_deleteproduct.getContentPane().setLayout(dlg_deleteproductLayout);
        dlg_deleteproductLayout.setHorizontalGroup(
            dlg_deleteproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_deleteproductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_deleteproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbox_deleteproduct_products, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dlg_deleteproductLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_deleteproduct_abbrechen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_deleteproduct_löschen)))
                .addContainerGap())
        );
        dlg_deleteproductLayout.setVerticalGroup(
            dlg_deleteproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_deleteproductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_deleteproduct_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlg_deleteproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteproduct_löschen)
                    .addComponent(btn_deleteproduct_abbrechen))
                .addContainerGap())
        );

        dlg_changeproduct.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlg_changeproductWindowActivated(evt);
            }
        });

        btn_changeproduct_abbrechen.setText("Abbrechen");
        btn_changeproduct_abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeproduct_abbrechenActionPerformed(evt);
            }
        });

        cbox_changeproduct_products.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_changeproduct_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_changeproduct_productsActionPerformed(evt);
            }
        });

        btn_changeproduct_ändern.setText("Ändern");
        btn_changeproduct_ändern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeproduct_ändernActionPerformed(evt);
            }
        });

        pnl_trans.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        lbl_cp_info_wert.setText("Betrag:");

        lbl_cp_info_kommentar.setText("Kommentar");

        txt_cp_info_kommentar.setText("kommentar");

        lbl_cp_info_name.setText("Name:");

        sp_cp_info_wert.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.5d)));
        sp_cp_info_wert.setEditor(new javax.swing.JSpinner.NumberEditor(sp_cp_info_wert, "0.00"));

        txt_cp_info_name.setText("name");

        javax.swing.GroupLayout pnl_transLayout = new javax.swing.GroupLayout(pnl_trans);
        pnl_trans.setLayout(pnl_transLayout);
        pnl_transLayout.setHorizontalGroup(
            pnl_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_transLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_cp_info_name)
                    .addComponent(lbl_cp_info_kommentar)
                    .addComponent(lbl_cp_info_wert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cp_info_kommentar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(sp_cp_info_wert)
                    .addComponent(txt_cp_info_name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_transLayout.setVerticalGroup(
            pnl_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_transLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cp_info_name)
                    .addComponent(txt_cp_info_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cp_info_wert)
                    .addComponent(sp_cp_info_wert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cp_info_kommentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cp_info_kommentar))
                .addContainerGap())
        );

        javax.swing.GroupLayout dlg_changeproductLayout = new javax.swing.GroupLayout(dlg_changeproduct.getContentPane());
        dlg_changeproduct.getContentPane().setLayout(dlg_changeproductLayout);
        dlg_changeproductLayout.setHorizontalGroup(
            dlg_changeproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_changeproductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_changeproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox_changeproduct_products, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_changeproductLayout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(btn_changeproduct_abbrechen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_changeproduct_ändern))
                    .addComponent(pnl_trans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dlg_changeproductLayout.setVerticalGroup(
            dlg_changeproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_changeproductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_changeproduct_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlg_changeproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_changeproduct_ändern)
                    .addComponent(btn_changeproduct_abbrechen))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Virtuelle Zahlung");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        cbox_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_productsActionPerformed(evt);
            }
        });

        lbl_produkt.setText("Produkt auswählen:");

        pnl_berechnungen.setBorder(javax.swing.BorderFactory.createTitledBorder("Berechnungen"));

        lbl_stück.setText("Stückzahl:");

        sp_stück.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sp_stückStateChanged(evt);
            }
        });

        btn_max.setText("Max. möglich:");
        btn_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maxActionPerformed(evt);
            }
        });

        lbl_preis.setText("Preis:");

        txt_preis.setEditable(false);

        lbl_restgeld.setText("Restl. Geld:");

        txt_restgeld.setEditable(false);

        javax.swing.GroupLayout pnl_berechnungenLayout = new javax.swing.GroupLayout(pnl_berechnungen);
        pnl_berechnungen.setLayout(pnl_berechnungenLayout);
        pnl_berechnungenLayout.setHorizontalGroup(
            pnl_berechnungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_berechnungenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_berechnungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_stück)
                    .addComponent(lbl_preis)
                    .addComponent(lbl_restgeld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_berechnungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_restgeld)
                    .addGroup(pnl_berechnungenLayout.createSequentialGroup()
                        .addComponent(sp_stück, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_max))
                    .addComponent(txt_preis))
                .addContainerGap())
        );
        pnl_berechnungenLayout.setVerticalGroup(
            pnl_berechnungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_berechnungenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_berechnungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_stück)
                    .addComponent(sp_stück, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_max))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_berechnungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preis)
                    .addComponent(txt_preis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_berechnungenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_restgeld)
                    .addComponent(txt_restgeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_newproduct.setText("Neu..");
        btn_newproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newproductActionPerformed(evt);
            }
        });

        btn_schliessen.setText("Schließen");
        btn_schliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_schliessenActionPerformed(evt);
            }
        });

        m_produkte.setText("Produkte");

        mitem_produkt_löschen.setText("Produkt löschen...");
        mitem_produkt_löschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_produkt_löschenActionPerformed(evt);
            }
        });
        m_produkte.add(mitem_produkt_löschen);

        mitem_produkt_ändern.setText("Produkt ändern...");
        mitem_produkt_ändern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_produkt_ändernActionPerformed(evt);
            }
        });
        m_produkte.add(mitem_produkt_ändern);

        jMenuBar1.add(m_produkte);

        m_einkauf.setText("Einkauf");

        mitem_einkauferstellen.setText("Einkauf erstellen...");
        m_einkauf.add(mitem_einkauferstellen);

        m_lookeinkauf.setText("Einkäufe ansehen");
        m_einkauf.add(m_lookeinkauf);

        jMenuBar1.add(m_einkauf);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_berechnungen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_produkt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_products, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_newproduct))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_schliessen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_produkt)
                    .addComponent(btn_newproduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_berechnungen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_schliessen)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cbox_products_refresh(cbox_products);
    }//GEN-LAST:event_formWindowActivated

    private void cbox_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_productsActionPerformed
        if (cbox_products.getSelectedItem() != null) {
			refresh_info();
			this.pack();
		}
		
    }//GEN-LAST:event_cbox_productsActionPerformed

    private void btn_newproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newproductActionPerformed
        dlg_newproduct.pack();
		dlg_newproduct.setLocationRelativeTo(null);
		dlg_newproduct.setVisible(true);
    }//GEN-LAST:event_btn_newproductActionPerformed

    private void btn_schliessen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_schliessen1ActionPerformed
		dlg_newproduct.dispose();
    }//GEN-LAST:event_btn_schliessen1ActionPerformed

    private void btn_hinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hinzufügenActionPerformed
        try {

            if (txt_np_name.getText().length() == 0 && (double) sp_np_wert.getValue() > 1) {
                MainMenu.errorBox(this, "Sie haben nicht alle nötigen Felder ausgefüllt!", "Füllen Sie alle Felder aus!");
            } else {
                MainMenu.SQL = "INSERT INTO patchowe_produkte (name, wert, kommentar) VALUES ( ?, ?, ?)";
                MainMenu.prepareStatement();
                MainMenu.stmt.setString(1, txt_np_name.getText());
                MainMenu.stmt.setDouble(2, (double) sp_np_wert.getValue());
                MainMenu.stmt.setString(3, txt_np_kommentar.getText());
                MainMenu.stmt.execute();
                MainMenu.infoBox(this, "Das Produkt " + txt_np_name.getText() + " wurde erfolgreich hinzugefügt!", "Produkt hinzugefügt!");
                MainMenu.stmt.closeOnCompletion();
                txt_np_name.setText("");
                sp_np_wert.setValue(0);
                txt_np_kommentar.setText("");
            }

        }
        catch (SQLException ex) {
            MainMenu.errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");

        }
    }//GEN-LAST:event_btn_hinzufügenActionPerformed

    private void mitem_produkt_löschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_produkt_löschenActionPerformed
        dlg_deleteproduct.pack();
		dlg_deleteproduct.setLocationRelativeTo(null);
		dlg_deleteproduct.setVisible(true);
    }//GEN-LAST:event_mitem_produkt_löschenActionPerformed

    private void btn_deleteproduct_löschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteproduct_löschenActionPerformed
        try {
            String sel;
            sel = cbox_deleteproduct_products.getSelectedItem().toString();
            String splitResult[] = sel.split(" ");

            MainMenu.SQL="DELETE FROM patchowe_produkte WHERE id = ?";
            MainMenu.prepareStatement();
            MainMenu.stmt.setString(1, splitResult[0]);
            MainMenu.stmt.execute();
            MainMenu.infoBox(this, "Das Produkt " + cbox_deleteproduct_products.getSelectedItem().toString() + " wurde erfolgreich aus der Datenbank gelöscht!",
                "Erfolgreich gelöscht!");
        } catch (SQLException ex) {
            errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
        }

    }//GEN-LAST:event_btn_deleteproduct_löschenActionPerformed

    private void btn_deleteproduct_abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteproduct_abbrechenActionPerformed
        dlg_deleteproduct.dispose();
    }//GEN-LAST:event_btn_deleteproduct_abbrechenActionPerformed

    private void dlg_deleteproductWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlg_deleteproductWindowActivated
        cbox_products_refresh(cbox_deleteproduct_products);
    }//GEN-LAST:event_dlg_deleteproductWindowActivated

    private void btn_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maxActionPerformed
        if (Maximalstück > 1) {
			sp_stück.setValue(Maximalstück);
		}
    }//GEN-LAST:event_btn_maxActionPerformed

    private void btn_schliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_schliessenActionPerformed
        dispose();
    }//GEN-LAST:event_btn_schliessenActionPerformed

    private void sp_stückStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sp_stückStateChanged
		berechnung();
    }//GEN-LAST:event_sp_stückStateChanged

    private void btn_changeproduct_abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeproduct_abbrechenActionPerformed
        dlg_changeproduct.dispose();
    }//GEN-LAST:event_btn_changeproduct_abbrechenActionPerformed

    private void btn_changeproduct_ändernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeproduct_ändernActionPerformed
        try {
			MainMenu.SQL = "UPDATE patchowe_produkte SET name = ?, wert = ?, kommentar = ? WHERE id = ?";
			MainMenu.prepareStatement();
			MainMenu.stmt.setString(1, txt_cp_info_name.getText());
			MainMenu.stmt.setDouble(2, (double) sp_cp_info_wert.getValue());
			MainMenu.stmt.setString(3, txt_cp_info_kommentar.getText());
			MainMenu.stmt.setInt(4, SelectedID);
			MainMenu.stmt.execute();
			infoBox(this, "Das Produkt '" + txt_cp_info_name.getText() + "' wurde erfolgreich geändert!", "Produkt geändert!");
			dlg_changeproduct.dispose();
		} catch (SQLException ex) {
			errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
		}
    }//GEN-LAST:event_btn_changeproduct_ändernActionPerformed

    private void dlg_changeproductWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlg_changeproductWindowActivated
        cbox_products_refresh(cbox_changeproduct_products);
    }//GEN-LAST:event_dlg_changeproductWindowActivated

    private void mitem_produkt_ändernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_produkt_ändernActionPerformed
        dlg_changeproduct.pack();
		dlg_changeproduct.setLocationRelativeTo(null);
		dlg_changeproduct.setVisible(true);
    }//GEN-LAST:event_mitem_produkt_ändernActionPerformed

    private void cbox_changeproduct_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_changeproduct_productsActionPerformed
        if (cbox_changeproduct_products.getSelectedItem() != null) {
			try {
			String sel;
			sel = cbox_changeproduct_products.getSelectedItem().toString();
			String[] splitResult = sel.split(" - ");
			SelectedID = Integer.parseInt(splitResult[0]);
			
			MainMenu.SQL = "SELECT name, wert, kommentar FROM patchowe_produkte WHERE id = ?";
			MainMenu.prepareStatement();
			MainMenu.stmt.setInt(1, SelectedID);
			rs_info = MainMenu.stmt.executeQuery();
			if (rs_info.next()) {
				txt_cp_info_name.setText(rs_info.getString("name"));
				sp_cp_info_wert.setValue(rs_info.getDouble("wert"));
				txt_cp_info_kommentar.setText(rs_info.getString("kommentar"));
			}
			
		} catch (SQLException ex) {
			Logger.getLogger(NewRepayment.class.getName()).log(Level.SEVERE, null, ex);
		}
		}
    }//GEN-LAST:event_cbox_changeproduct_productsActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VirtualPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VirtualPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VirtualPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VirtualPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VirtualPay().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changeproduct_abbrechen;
    private javax.swing.JButton btn_changeproduct_ändern;
    private javax.swing.JButton btn_deleteproduct_abbrechen;
    private javax.swing.JButton btn_deleteproduct_löschen;
    private javax.swing.JButton btn_hinzufügen;
    private javax.swing.JButton btn_max;
    private javax.swing.JButton btn_newproduct;
    private javax.swing.JButton btn_schliessen;
    private javax.swing.JButton btn_schliessen1;
    private javax.swing.JComboBox<String> cbox_changeproduct_products;
    private javax.swing.JComboBox<String> cbox_deleteproduct_products;
    private javax.swing.JComboBox<String> cbox_products;
    private javax.swing.JDialog dlg_changeproduct;
    private javax.swing.JDialog dlg_deleteproduct;
    private javax.swing.JDialog dlg_newproduct;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_cp_info_kommentar;
    private javax.swing.JLabel lbl_cp_info_name;
    private javax.swing.JLabel lbl_cp_info_wert;
    private javax.swing.JLabel lbl_np_kommentar;
    private javax.swing.JLabel lbl_np_name;
    private javax.swing.JLabel lbl_np_wert;
    private javax.swing.JLabel lbl_preis;
    private javax.swing.JLabel lbl_produkt;
    private javax.swing.JLabel lbl_restgeld;
    private javax.swing.JLabel lbl_stück;
    private javax.swing.JMenu m_einkauf;
    private javax.swing.JMenu m_lookeinkauf;
    private javax.swing.JMenu m_produkte;
    private javax.swing.JMenuItem mitem_einkauferstellen;
    private javax.swing.JMenuItem mitem_produkt_löschen;
    private javax.swing.JMenuItem mitem_produkt_ändern;
    private javax.swing.JPanel pnl_berechnungen;
    private javax.swing.JPanel pnl_trans;
    private javax.swing.JSpinner sp_cp_info_wert;
    private javax.swing.JSpinner sp_np_wert;
    private javax.swing.JSpinner sp_stück;
    private javax.swing.JTextField txt_cp_info_kommentar;
    private javax.swing.JTextField txt_cp_info_name;
    private javax.swing.JTextField txt_np_kommentar;
    private javax.swing.JTextField txt_np_name;
    private javax.swing.JTextField txt_preis;
    private javax.swing.JTextField txt_restgeld;
    // End of variables declaration//GEN-END:variables

	private void cbox_products_refresh(JComboBox<String> combobox) {
		try {
			MainMenu.SQL = "SELECT id, name FROM patchowe_produkte";
			MainMenu.prepareStatement();
			rs_products = MainMenu.stmt.executeQuery();
			combobox.removeAllItems();
			while (rs_products.next()) {
				combobox.addItem(rs_products.getString("id") + " - " + rs_products.getString("name"));
			}
			//if (si_friends >= 0) {
				//cbox_freund.setSelectedIndex(si_friends);
			//}
		} catch (SQLException ex) {
			MainMenu.errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
		}
	}

	private void refresh_info() {
		try {
			String sel;
            sel = cbox_products.getSelectedItem().toString();
            String splitResult[] = sel.split(" - ");
			
			MainMenu.SQL = "SELECT wert FROM patchowe_produkte WHERE id = ?";
			MainMenu.prepareStatement();
			MainMenu.stmt.setInt(1, Integer.parseInt(splitResult[0]));
			rs_info = MainMenu.stmt.executeQuery();
			rs_info.next();
			Produktwert = rs_info.getDouble(1);
			if (MainMenu.getvariable("GB_Bar") != null && MainMenu.getvariable("GB_Bankomat") != null) {
				Kapital = Double.parseDouble(MainMenu.p.getProperty("GB_Bar")) + Double.parseDouble(MainMenu.p.getProperty("GB_Bankomat"));
				Maximalstück = Math.floor(Kapital / Produktwert);
			}
			btn_max.setText("Max. möglich: " + n.format(Maximalstück));
			SpinnerModel sm = new SpinnerNumberModel(1, 1, Maximalstück, 1);
			sp_stück.setModel(sm);
			berechnung();
			//if (si_friends >= 0) {
				//cbox_freund.setSelectedIndex(si_friends);
			//}
		} catch (SQLException ex) {
			MainMenu.errorBox(this, "Ein Fehler ist aufgetreten.\nFehlermeldung:\n'" + ex.getMessage() + "'", "Fehler!");
		}
	}

	private void berechnung() {
		Gesamtpreis = Produktwert * Double.parseDouble(sp_stück.getValue().toString());
		txt_preis.setText(euro.format(Gesamtpreis));
		txt_restgeld.setText(euro.format(Kapital - Gesamtpreis));
	}
}
